swagger: '2.0'
info:
  description: |
    Cryptocurrency Manager, you can find 
    out more about CryMa at 
    [https://github.com/cipriancus/CryMa](https://github.com/cipriancus/CryMa )
  version: 1.0.0
  title: CryMa
  license:
    name: MIT
    url: https://github.com/cipriancus/CryMa/blob/master/LICENSE
# host: https://github.com/cipriancus/CryMa
# basePath: /v2
tags:
- name: CryMa
  description: Cryptocurrency Manager
  externalDocs:
    description: Find out more
    url: https://github.com/cipriancus/CryMa
- name: busaco
  description: Buraga Sabin's website
  externalDocs :
    description : Buraga Sabin's website
    url : https://profs.info.uaic.ro/~busaco/
# schemes:
# - http
paths:
  /cointology:
    get:
      tags:
      - Cointology
      summary: Returns all coins
      operationId: getCoin
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: Item limit, default 25
        type: string
      - name: format
        in: query
        description: Format of output (JSON-LD, XML etc) JSON-LD default
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
                $ref: '#/definitions/Coin'
        400 :
          description: invalid parameters provided
  /cointology/{abbreviation}:
    get:
      tags:
      - Cointology
      summary: Get coin from the system using abbreviation
      parameters:
      - name: abbreviation
        in: path
        description: Coin Id of coin (BTC)
        required: true
        type : string
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
                $ref: '#/definitions/Coin'
        400:
          description: Invalid coin id supplied
  /news:
    get:
      tags:
      - News
      summary: Get latest news
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: Number of news to return. 25 Default.
        required: false
        type: string
      - name: format
        in: query
        description: Format of output (JSON-LD, XML etc) JSON-LD default
        required: false
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items :  
              $ref: '#/definitions/News'
  /news/coin/{abbreviation}:
    get:
      tags:
      - News
      summary: Get news by coin abbreviation
      produces:
      - application/json
      parameters:
      - name: abbreviation
        in: path
        description: The news that needs to be fetched by abbreviation. (BTC)
        required: true
        type: string
      - name: limit
        in: query
        description: The number of news to return, 25 by default
        required: false
        type: string
      - name: format
        in: query
        description: Format of output (JSON-LD, XML etc) JSON-LD default
        required: false
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/News'
  /plot/{abbreviation}:
    get:
      tags:
      - Plot
      summary: Provides data for the price evolution chart
      produces:
      - application/json
      parameters:
      - name: abbreviation
        in: path
        description : The coin abbreviation that is searched (BTC)
        required : true
        type: string
      - name: startDate
        in: query
        description: The start date for the data.
        required: true
        type: string
      - name: endDate
        in: query
        description: The end date for the data.
        required: true
        type: string
      - name: format
        in: query
        description: Format of output (JSON-LD, XML etc) JSON-LD default
        required: false
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items :  
              $ref: '#/definitions/CoinValue'
  /coin:
    get:
      tags:
      - Plot
      summary: Returns all coins, with all values and detailed instruction on how to use links
      produces:
      - application/json
      parameters:
      - name: page
        in: query
        description: The page number
        type: string
      - name: size
        in: query
        description: Items per page
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items :  
              $ref: '#/definitions/TopCoin'
    post:
      tags:
      - Plot
      summary: Create a new top coin
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items :  
              $ref: '#/definitions/TopCoin'
  /coin/{coin-id}:
    get:
      tags:
      - Plot
      summary: Provides data for the top currency chart for a specific coin by coin-id
      produces:
      - application/json
      parameters:
      - name: coin-id
        in: path
        description : The coin id that is searched.
        required : true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items :  
              $ref: '#/definitions/TopCoin'
    delete:
      tags:
      - Plot
      summary: delete existing coin
      produces:
      - application/json
      parameters:
      - name: coin-id
        in: path
        description : The coin id that is searched.
        required : true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items :  
              $ref: '#/definitions/TopCoin'
  /predict/{abbreviation}:
    get:
      tags:
      - Plot
      summary: Provides data for the price evolution prediction values for a specific coin
      produces:
      - application/json
      parameters:
      - name: abbreviation
        in: path
        description : The coin abbreviation that is searched.
        required : true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items :  
              $ref: '#/definitions/Prediction'
definitions:
  Coin:
    type: object
    properties:
      abbreviation : 
        type : string
        example : BTC
      capital :
        type : integer
        format : float
        example: 1.92156418192E11
      supply :
        type : integer
        format : float
        example: 1.6825275E7
      change :
        type : integer
        format : float
        example: 3.68
      price :
        type : integer
        format : float
        example: 11420.7
      volume :
        type : integer
        format : float
        example: 1.08833E10
      values :
        type : array
        items:
                $ref: '#/definitions/CoinValue'
    xml:
      name: Coin
  CoinValue:
    type: object
    required:
    - abbreviation
    - value
    - dateTime
    properties:
      abbreviation : 
        type : string
        example : BTC
      value :
        type : integer
        format : float
        example: 123
      dateTime :
        type: string
        example: "2018-01-12T21:32:52+02:00"
    xml:
      name: CoinValue
  TopCoin:
    type: object
    required:
    - id
    - name
    - marketCap
    - price
    - supply
    - volume
    - change
    properties:
      id:
        type: integer
        format: int64
        example: 1234 
      name:
        type: string
        example : BTC
      marketCap:
        type : integer
        format : float
        example : 14.5
      price:
        type : integer
        format : float
        example : 15.6
      supply:
        type : integer
        format : float
        example : 15.6
      volume:
        type : integer
        format : float
        example : 50  
      change:
        type : integer
        format : float
        example : 15.6
    xml:
      name: TopCoin
  Prediction:
    type: object
    required:
    - abbreviation
    - value
    - date
    properties:
      abbreviation:
        type: string
        example : "BTC"
      value:
        type : integer
        format : float
        example : 1234
      dateTime:
        type: string
        example : "2018-01-12T21:32:52+02:00"
    xml:
      name: Prediction
  News:
    type: object
    required:
    - id
    - title
    - urlSource
    - shortText
    - longText
    properties:
      name:
        type: string
        example: Bitcoin Cash Skyrockets
      url:
        type : string
        example : https://www.forbes.com/sites/laurashin/2017/11/12/bitcoin-cash-skyrockets-bitcoin-price-drops-as-civil-war-continues/#1f26873e35b5
      description :
        type : string
        example : The surge by Bitcoin Cash led it to overtake Ethereum in market capitalization to $40 billion and become the second-largest crypto [...]
      date :
        type: string
        example: "2018-01-12T21:32:52+02:00"
    xml:
      name: News
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
host: virtserver.swaggerhub.com
basePath: /cipriancus1/CryMa/1.0.0
schemes:
 - https
 - http