---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: crymaservice
  ports:
    - name: eureka
      port: 80
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: crymaservice
spec:
  type: ClusterIP
  selector:
    app: cryma
  ports:
    - name: eureka
      port: 8081
      targetPort: 8081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cryma-eureka
spec:
  template:
    metadata:
      labels:
        app: cryma-eureka
    spec:
      containers:
        - name: cryma-eureka
          image: cipriancus/cryma-eureka:latest
          ports:
            - containerPort: 8081

