
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cryma-eureka
spec:
  template:
    metadata:
      labels:
        app: cryma-eureka
    spec:
      containers:
        - name: cryma-eureka
          image: cipriancus/cryma-eureka:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cryma-eureka
  name: cryma-eureka-service
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: cryma-eureka
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cryma-eureka-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: cryma-eureka
  ports:
    - name: eureka
      port: 8081
      targetPort: 8081


