spring:
   application:
      name: cryma-zuul-apigateway

server:
  port: 8081

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8080/eureka/

zuul:
  prefix: /api
  routes:
    cryma-python-prediction:
      path: /cryma-python-prediction/**
      serviceId: cryma-python-prediction
    cryma-prediction:
      path: /cryma-prediction/**
      serviceId: cryma-prediction

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true